# Generated by Django 5.2.13 on 2026-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Inventory',
                'verbose_name_plural': 'Amazon Inventory',
                'db_table': 'amazon_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmazonSecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Secondary Sales',
                'verbose_name_plural': 'Amazon Secondary Sales',
                'db_table': 'amazon_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BigbasketInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bigbasket Inventory',
                'verbose_name_plural': 'Bigbasket Inventory',
                'db_table': 'bigbasket_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BigbasketSecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bigbasket Secondary Sales',
                'verbose_name_plural': 'Bigbasket Secondary Sales',
                'db_table': 'bigbasket_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlinkitInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blinkit Inventory',
                'verbose_name_plural': 'Blinkit Inventory',
                'db_table': 'blinkit_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlinkitSecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blinkit Secondary Sales',
                'verbose_name_plural': 'Blinkit Secondary Sales',
                'db_table': 'blinkit_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlipkartInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flipkart Inventory',
                'verbose_name_plural': 'Flipkart Inventory',
                'db_table': 'flipkart_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlipkartSecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flipkart Secondary Sales',
                'verbose_name_plural': 'Flipkart Secondary Sales',
                'db_table': 'flipkart_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JiomartInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jiomart Inventory',
                'verbose_name_plural': 'Jiomart Inventory',
                'db_table': 'jiomart_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JiomartSecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jiomart Secondary Sales',
                'verbose_name_plural': 'Jiomart Secondary Sales',
                'db_table': 'jiomart_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterPO',
            fields=[
                ('platform', models.CharField(max_length=40)),
                ('po_number', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Master PO',
                'verbose_name_plural': 'Master POs',
                'db_table': 'master_po',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwiggyInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Swiggy Inventory',
                'verbose_name_plural': 'Swiggy Inventory',
                'db_table': 'swiggy_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwiggySecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Swiggy Secondary Sales',
                'verbose_name_plural': 'Swiggy Secondary Sales',
                'db_table': 'swiggy_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZeptoInventory',
            fields=[
                ('sku', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zepto Inventory',
                'verbose_name_plural': 'Zepto Inventory',
                'db_table': 'zepto_inventory',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZeptoSecondary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zepto Secondary Sales',
                'verbose_name_plural': 'Zepto Secondary Sales',
                'db_table': 'zepto_secondary',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
