# Generated by Django 5.2.14 on 2026-05-19 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinDohDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.TextField(blank=True)),
                ('year', models.IntegerField(null=True)),
                ('asin', models.TextField()),
                ('units_sold', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('ltr_sold', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('soh_unit', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('soh_ltr', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('drr_unit', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('drr_ltr', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('doh', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sp_asin_doh_daily',
                'unique_together': {('date', 'asin')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.TextField(blank=True)),
                ('appointment_time', models.DateTimeField(null=True)),
                ('destination_fc', models.TextField(blank=True)),
                ('pro', models.TextField(blank=True)),
                ('truck_size', models.CharField(blank=True, max_length=16)),
                ('truck_capacity_liters', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('planned_liters', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('load_percentage', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('auto_planned', models.BooleanField(default=False)),
                ('vehicle_type', models.TextField(blank=True)),
                ('driver_name', models.TextField(blank=True)),
                ('driver_phone', models.TextField(blank=True)),
                ('vehicle_number', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='draft', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shipments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.TextField()),
                ('change_type', models.TextField()),
                ('old_asin', models.TextField(blank=True)),
                ('new_asin', models.TextField(blank=True)),
                ('old_sku', models.TextField(blank=True)),
                ('new_sku', models.TextField(blank=True)),
                ('old_qty', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('new_qty', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('reason', models.TextField()),
                ('reason_note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='shipment.shipment')),
            ],
            options={
                'db_table': 'sp_audit_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.TextField(blank=True)),
                ('po_number', models.TextField(blank=True)),
                ('asin', models.TextField(blank=True)),
                ('internal_sku', models.TextField(blank=True)),
                ('product_name', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('sub_category', models.TextField(blank=True)),
                ('brand', models.TextField(blank=True)),
                ('item_head', models.TextField(blank=True)),
                ('item', models.TextField(blank=True)),
                ('availability_status', models.TextField(blank=True)),
                ('po_status', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('accepted_qty', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('available_qty', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('planned_qty', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('planned_liters', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('per_liter', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('case_pack', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('doh', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('drr_unit', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('soh_unit', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('days_to_expiry', models.IntegerField(null=True)),
                ('priority_bucket', models.TextField(blank=True)),
                ('priority_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('priority_reason', models.TextField(blank=True)),
                ('is_auto_selected', models.BooleanField(default=True)),
                ('is_changed', models.BooleanField(default=False)),
                ('change_reason', models.TextField(blank=True)),
                ('not_loaded', models.BooleanField(default=False)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipment.shipment')),
            ],
            options={
                'db_table': 'sp_items',
            },
        ),
    ]
