# Generated by Django 5.2.14 on 2026-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_dispatch_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='destination_fc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
