# Generated by Django 5.2.14 on 2026-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_shipmentitem_destination_fc_shipmentitem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='planning_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('appointment', 'With Appointment'), ('doh', 'With DOH')], default='manual', max_length=16),
        ),
    ]
