# Generated by Django 5.2.14 on 2026-05-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_shipment_planning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='additional_appointment_ids',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='appointments_meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
