# Generated by Django 5.2.14 on 2026-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_po_fc_flip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(condition=models.Q(('not_loaded', False)), fields=['asin', 'po_number'], name='sp_items_loaded_asin_po'),
        ),
    ]
