# Generated by Django 5.2.14 on 2026-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_sp_items_loaded_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='short_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='unfit_reason',
            field=models.TextField(blank=True),
        ),
    ]
