# Generated by Django 5.2.15 on 2026-07-15 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0011_shipmentitem_source_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('data', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_documents', to='shipment.shipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_po_document',
                'ordering': ['po_number'],
                'unique_together': {('shipment', 'po_number')},
            },
        ),
    ]
