# Generated by Django 5.2.15 on 2026-07-17 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0013_shipmentinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=32)),
                ('planning_mode', models.CharField(blank=True, max_length=16)),
                ('appointment_id', models.TextField(blank=True)),
                ('destination_fc', models.TextField(blank=True)),
                ('loaded_item_count', models.IntegerField(default=0)),
                ('planned_liters', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('created_by_email', models.TextField(blank=True)),
                ('deleted_by_email', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_deletion_log',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
