# Generated by Django 5.2.15 on 2026-07-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0014_shipmentdeletionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentinvoice',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='shipmentinvoice',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipmentinvoice',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shipment.shipment'),
        ),
    ]
