# Generated by Django 5.2.15 on 2026-07-31 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0015_alter_shipmentinvoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='switch_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_email_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_state',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for Switching'), ('email_failed', 'Switch Email Failed'), ('verified', 'Switch Verified'), ('rejected', 'Switch Rejected')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_verified_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_verify_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='switch_verify_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(condition=models.Q(('switch_state', ''), _negated=True), fields=['switch_state'], name='sp_shipments_switch_idx'),
        ),
    ]
