"""Column ordering helpers for Primary Master PO sheet-style responses."""

PRIMARY_MASTER_PO_COLUMNS = (
    "po_number",
    "po_date",
    "po_expiry_date",
    "delivery_date",
    "appointment_date",
    "vendor_name",
    "status",
    "remarks",
    "sku_code",
    "sku_name",
    "order_qty",
    "delivered_qty",
    "basic_rate",
    "landing_rate",
    "location",
    "format",
    "lead_time",
    "days_to_expiry",
    "po_window",
    "po_status",
    "item_status",
    "vendor_new",
    "item",
    "sap_sku_name",
    "sap_sku_code",
    "category",
    "sub_category",
    "case_pack",
    "per_liter",
    "total_order_liters",
    "total_delivered_liters",
    "total_order_amt_inclusive",
    "total_deliver_amt_inclusive",
    "po_month",
    "delivery_month",
    "year",
    "item_head",
    "city",
    "state",
    "distributor_margin",
    "realise",
    "distributor_commission_per_unit",
    "total_distributor_commission",
    "brand",
    "category_head",
    "unit_of_measure",
    "open_close",
    "total_order_amt_exclusive",
    "total_delivered_amt_exclusive",
    "total_order_amt_without_margin",
    "total_delivered_amt_without_margin",
    "missed_qty",
    "filled_qty",
    "missed_ltrs",
    "filled_ltrs",
    "missed_amt",
    "filled_amt",
    "order_qty_cl",
    "order_ltrs_cl",
    "order_amt_cl",
    "qty_fill_rate_pct",
    "qty_miss_rate_pct",
    "ltrs_fill_rate_pct",
    "ltrs_miss_rate_pct",
)

PRIMARY_MASTER_PO_LABELS = {
    "po_number": "PO Number",
    "po_date": "PO Date",
    "po_expiry_date": "PO Expiry Date",
    "delivery_date": "Delivery Date",
    "appointment_date": "Appointment Date",
    "vendor_name": "Vendor Name",
    "status": "Status",
    "remarks": "Remarks",
    "sku_code": "SKU Code",
    "sku_name": "SKU Name",
    "order_qty": "Order Qty",
    "delivered_qty": "Delivered Qty",
    "basic_rate": "Basic Rate",
    "landing_rate": "landing Rate",
    "location": "Location",
    "format": "Format",
    "lead_time": "Lead Time",
    "days_to_expiry": "Days To Expiry",
    "po_window": "Po Window",
    "po_status": "PO Status",
    "item_status": "Item Status",
    "vendor_new": "Vendor_New",
    "item": "ITEM",
    "sap_sku_name": "SAP SKU NAME",
    "sap_sku_code": "SAP SKU Code",
    "category": "Category",
    "sub_category": "Sub Category",
    "case_pack": "Case Pack",
    "per_liter": "Per Liter",
    "total_order_liters": "Total Order Liters",
    "total_delivered_liters": "Total Delivered Liters",
    "total_order_amt_inclusive": "Total Order Amt (INCLUSIVE)",
    "total_deliver_amt_inclusive": "Total Deliver Amt (INCLUSIVE)",
    "po_month": "PO Month",
    "delivery_month": "Delivery Month",
    "year": "Year",
    "item_head": "Item Head",
    "city": "City",
    "state": "State",
    "distributor_margin": "Distributor Margin",
    "realise": "Realise",
    "distributor_commission_per_unit": "Distributor Commision Per Unit",
    "total_distributor_commission": "Total Distributor Commission",
    "brand": "Brand",
    "category_head": "Category Head",
    "unit_of_measure": "Unit of Measure",
    "open_close": "Open/Close",
    "total_order_amt_exclusive": "TOTAL ORDER AMT (EXCLUSIVE)",
    "total_delivered_amt_exclusive": "TOTAL DELIVERED AMT EXCLUSIVE",
    "total_order_amt_without_margin": "TOTAL ORDER AMT (WITHOUT MARGIN)",
    "total_delivered_amt_without_margin": "TOTAL DELIVERED AMT (WITHOUT MARGIN)",
    "missed_qty": "MISSED QTY",
    "filled_qty": "FILLED QTY",
    "missed_ltrs": "MISSED LTRS",
    "filled_ltrs": "FILLED LTRS",
    "missed_amt": "MISSED AMT",
    "filled_amt": "FILLED AMT",
    "order_qty_cl": "ORDER QTY - CL",
    "order_ltrs_cl": "ORDER LTRS - CL",
    "order_amt_cl": "ORDER AMT - CL",
    "qty_fill_rate_pct": "QTY FILL RATE %",
    "qty_miss_rate_pct": "QTY MISS RATE %",
    "ltrs_fill_rate_pct": "LTRS FILL RATE %",
    "ltrs_miss_rate_pct": "LTRS MISS RATE %",
}

PRIMARY_MASTER_PO_TABLES = {"master_po", "prim_master_po", "test_master_po"}


def order_primary_master_po_columns(columns):
    """Return columns in sheet order, preserving unknown columns at the end."""
    available = list(columns or [])
    available_set = set(available)
    ordered = [column for column in PRIMARY_MASTER_PO_COLUMNS if column in available_set]
    ordered.extend(column for column in available if column not in PRIMARY_MASTER_PO_COLUMNS)
    return ordered


def order_primary_master_po_row(row: dict) -> dict:
    """Return a dict whose insertion order follows the Master PO sheet order."""
    ordered_columns = order_primary_master_po_columns(row.keys())
    return {column: row.get(column) for column in ordered_columns}


def primary_master_po_labels(columns):
    return {column: PRIMARY_MASTER_PO_LABELS.get(column, column) for column in columns or []}
