# Generated by Django 5.2.15 on 2026-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SapBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=64)),
                ('sap_item_code', models.CharField(max_length=64)),
                ('billed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('invoices', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sap_billing',
                'indexes': [models.Index(fields=['po_number'], name='sap_billing_po_idx')],
                'constraints': [models.UniqueConstraint(fields=('po_number', 'sap_item_code'), name='sap_billing_po_item_uq')],
            },
        ),
    ]
